AllCops:
  Exclude:
    - "spec/**/*"
    - "node_modules/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "lib/**/*"
    - "config/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/AccessModifierIndentation:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/ExtraSpacing:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Layout/LineLength:
  Max: 99

Metrics/AbcSize:
  Enabled: false

Style/Encoding:
  Enabled: false

Layout/LineLength:
  Max: 99

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 20

Style/RedundantPercentQ:
  Enabled: false
