langauge: ruby
before_install:
  - nvm install node
rbenv:
  - 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
before_script:
  - rm -rf spec/cassettes
script:
  - yarn add stimulus
  - bundle exec rails db:{create,migrate} RAILS_ENV=test
  - bundle exec rspec
